name: Build Android app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
    - name: Build
      run: ionic cordova build android --prod
